/**
 * code-panel.js — Code Panel (右侧代码展示面板)
 *
 * Features:
 *   - File tree for current session files
 *   - Syntax highlighted code preview
 *   - Collapsible code blocks (expand/collapse)
 *   - Download, copy, and GitHub sync actions
 *   - Real-time sync via SSE events
 *   - Diff view (current vs history)
 *
 * Events consumed (via window.dispatchEvent / custom events):
 *   - 'code:file_added'    → { path, content, language }
 *   - 'code:file_updated'  → { path, content, language }
 *   - 'code:file_deleted'  → { path }
 *   - 'code:session_clear' → {}
 *   - 'code:sync_state'    → { files: [...] }
 *
 * Usage:
 *   // Register an event
 *   window.addEventListener('code:file_added', (e) => { ... });
 *   // Or call directly
 *   window.CodePanel.addFile({ path: 'main.py', content: '...', language: 'python' });
 */

(function () {
  'use strict';

  // ─── State ─────────────────────────────────────────────────────────────────

  const _state = {
    files: {},           // { path: { path, content, language, updatedAt } }
    selectedPath: null,
    expandedPaths: new Set(),
    streamingFiles: {},   // files being streamed in real-time
  };

  // ─── Language Detection ────────────────────────────────────────────────────

  const LANG_MAP = {
    py: 'python', js: 'javascript', ts: 'typescript',
    jsx: 'jsx', tsx: 'tsx', html: 'html', css: 'css',
    json: 'json', md: 'markdown', yaml: 'yaml', yml: 'yaml',
    sh: 'bash', bash: 'bash', sql: 'sql', go: 'go',
    rs: 'rust', java: 'java', cpp: 'cpp', c: 'c',
    rb: 'ruby', php: 'php', swift: 'swift', kt: 'kotlin',
    toml: 'toml', xml: 'xml', txt: 'text',
  };

  function detectLanguage(filename) {
    const ext = (filename.split('.').pop() || '').toLowerCase();
    return LANG_MAP[ext] || 'text';
  }

  function getFileIcon(filename) {
    const ext = (filename.split('.').pop() || '').toLowerCase();
    const icons = {
      py: 'fa-brands fa-python', js: 'fa-brands fa-js', ts: 'fa-brands fa-js',
      jsx: 'fa-brands fa-react', tsx: 'fa-brands fa-react',
      html: 'fa-brands fa-html5', css: 'fa-brands fa-css3-alt',
      json: 'fa-solid fa-brackets-curly', md: 'fa-brands fa-markdown',
      yaml: 'fa-solid fa-file-code', yml: 'fa-solid fa-file-code',
      sh: 'fa-solid fa-terminal', bash: 'fa-solid fa-terminal',
      sql: 'fa-solid fa-database', go: 'fa-solid fa-golang',
      rs: 'fa-solid fa-rust', java: 'fa-brands fa-java',
      toml: 'fa-solid fa-gear', xml: 'fa-solid fa-code',
    };
    return icons[ext] || 'fa-solid fa-file';
  }

  // ─── Escape HTML ───────────────────────────────────────────────────────────

  function escHtml(str) {
    if (!str) return '';
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  // ─── File Tree ─────────────────────────────────────────────────────────────

  function buildTree(files) {
    const root = { _children: {}, _type: 'root' };
    Object.keys(files).forEach(function (path) {
      const parts = path.replace(/\\/g, '/').split('/').filter(Boolean);
      let cur = root;
      parts.forEach(function (part, i) {
        if (!cur._children[part]) {
          cur._children[part] = {
            _children: {},
            _type: i === parts.length - 1 ? 'file' : 'folder',
            _path: path,
          };
        }
        cur = cur._children[part];
      });
    });
    return root;
  }

  function sortTree(node) {
    const keys = Object.keys(node._children).sort(function (a, b) {
      const ca = node._children[a], cb = node._children[b];
      if (ca._type !== cb._type) return ca._type === 'folder' ? -1 : 1;
      return a.localeCompare(b);
    });
    const sorted = {};
    keys.forEach(function (k) { sortTree(node._children[k]); sorted[k] = node._children[k]; });
    node._children = sorted;
  }

  function renderFileTree(container) {
    if (!container) return;
    const entries = Object.keys(_state.files);
    if (entries.length === 0) {
      container.innerHTML = '<div class="cp-empty"><i class="fa-solid fa-code"></i><p>No files yet</p><span>Files generated by the agent will appear here</span></div>';
      return;
    }

    const tree = buildTree(_state.files);
    sortTree(tree);
    container.innerHTML = renderTreeNode(tree, 0);
  }

  function renderTreeNode(node, depth) {
    let html = '';
    Object.keys(node._children).forEach(function (key) {
      const child = node._children[key];
      const indent = depth * 14;
      if (child._type === 'file') {
        const isActive = _state.selectedPath === child._path;
        const f = _state.files[child._path] || {};
        const icon = getFileIcon(child._path);
        const lineCount = (f.content || '').split('\n').length;
        html += '<div class="cp-tree-row' + (isActive ? ' active' : '') + '" ' +
          'style="padding-left:' + indent + 'px" ' +
          'onclick="window.CodePanel.selectFile(\'' + escAttr(child._path) + '\')">';
        html += '<span class="cp-tree-indent"></span>';
        html += '<i class="fa-solid ' + icon + ' cp-file-icon"></i>';
        html += '<span class="cp-file-name">' + escHtml(key) + '</span>';
        html += '<span class="cp-file-meta">' + lineCount + 'L</span>';
        html += '<span class="cp-file-actions">';
        html += '<button onclick="event.stopPropagation();window.CodePanel.copyFile(\'' + escAttr(child._path) + '\')" title="Copy"><i class="fa-solid fa-copy"></i></button>';
        html += '<button onclick="event.stopPropagation();window.CodePanel.downloadFile(\'' + escAttr(child._path) + '\')" title="Download"><i class="fa-solid fa-download"></i></button>';
        html += '</span>';
        html += '</div>';
      } else {
        const isOpen = _state.expandedPaths.has(child._path);
        html += '<div class="cp-tree-row cp-folder-row' + (isOpen ? ' open' : '') + '" ' +
          'style="padding-left:' + indent + 'px" ' +
          'onclick="window.CodePanel.toggleFolder(\'' + escAttr(key) + '\', this)">';
        html += '<span class="cp-tree-indent"></span>';
        html += '<i class="fa-solid fa-chevron-right cp-chevron' + (isOpen ? ' open' : '') + '"></i>';
        html += '<i class="fa-solid fa-folder cp-folder-icon' + (isOpen ? ' open' : '') + '"></i>';
        html += '<span class="cp-folder-name">' + escHtml(key) + '</span>';
        html += '</div>';
        if (isOpen) {
          html += '<div class="cp-tree-children">' + renderTreeNode(child, depth + 1) + '</div>';
        }
      }
    });
    return html;
  }

  // ─── Code Preview ──────────────────────────────────────────────────────────

  function renderPreview(container) {
    if (!container) return;
    const f = _state.selectedPath ? _state.files[_state.selectedPath] : null;

    if (!f) {
      container.innerHTML = '<div class="cp-preview-empty">' +
        '<i class="fa-solid fa-code"></i>' +
        '<p>Select a file to preview</p>' +
        '</div>';
      return;
    }

    const lang = f.language || detectLanguage(f.path);
    const content = f.content || '';
    const lines = content.split('\n');
    const isLong = lines.length > 20 || content.length > 2000;
    const shortContent = lines.slice(0, 20).join('\n');

    let codeHtml;
    if (isLong) {
      codeHtml = '<div class="cp-preview-collapsed">' +
        '<div class="cp-preview-short">' + escHtml(shortContent) + '<span class="cp-ellipsis">...</span></div>' +
        '<pre class="cp-preview-full" style="display:none">' + escHtml(content) + '</pre></div>';
    } else {
      codeHtml = '<pre class="cp-preview-code">' + escHtml(content) + '</pre>';
    }

    const lineNumberWidth = String(lines.length).length;
    const linesHtml = lines.map(function (line, i) {
      const num = String(i + 1).padStart(lineNumberWidth, ' ');
      return '<div class="cp-code-line"><span class="cp-line-num">' + num + '</span><span class="cp-line-content">' + escHtml(line || ' ') + '</span></div>';
    }).join('');

    container.innerHTML =
      '<div class="cp-preview-header">' +
        '<div class="cp-preview-header-left">' +
          '<i class="fa-solid ' + getFileIcon(f.path) + '"></i>' +
          '<span class="cp-preview-filename">' + escHtml(f.path) + '</span>' +
          '<span class="cp-preview-lang">' + lang + '</span>' +
        '</div>' +
        '<div class="cp-preview-header-actions">' +
          (isLong ? '<button class="cp-action-btn" onclick="window.CodePanel.togglePreview(this)"><i class="fa-solid fa-eye"></i> Expand</button>' : '') +
          '<button class="cp-action-btn" onclick="window.CodePanel.copyFile(\'' + escAttr(f.path) + '\')"><i class="fa-solid fa-copy"></i></button>' +
          '<button class="cp-action-btn" onclick="window.CodePanel.downloadFile(\'' + escAttr(f.path) + '\')"><i class="fa-solid fa-download"></i></button>' +
          '<button class="cp-action-btn" onclick="window.CodePanel.syncToGitHub(\'' + escAttr(f.path) + '\')"><i class="fa-brands fa-github"></i></button>' +
        '</div>' +
      '</div>' +
      '<div class="cp-preview-body" id="cp-preview-body">' +
        '<div class="cp-code-container lang-' + lang + '">' +
          linesHtml +
        '</div>' +
      '</div>' +
      '<div class="cp-preview-footer">' +
        '<span>' + lines.length + ' lines</span>' +
        '<span>' + content.length + ' chars</span>' +
        '<span>Modified ' + (f.updatedAt ? formatTime(f.updatedAt) : 'just now') + '</span>' +
      '</div>';
  }

  function togglePreview(btn) {
    const header = btn.closest('.cp-preview-header');
    const body = document.getElementById('cp-preview-body');
    if (!body) return;
    const collapsed = body.querySelector('.cp-preview-collapsed');
    const full = body.querySelector('.cp-preview-full');
    const short = body.querySelector('.cp-preview-short');
    if (!collapsed) return;

    const isShowingShort = short && short.style.display !== 'none';
    if (isShowingShort) {
      if (short) short.style.display = 'none';
      if (full) full.style.display = '';
      if (btn) { btn.innerHTML = '<i class="fa-solid fa-eye-slash"></i> Collapse'; btn.classList.add('active'); }
    } else {
      if (short) short.style.display = '';
      if (full) full.style.display = 'none';
      if (btn) { btn.innerHTML = '<i class="fa-solid fa-eye"></i> Expand'; btn.classList.remove('active'); }
    }
  }

  // ─── Streaming Preview (real-time file as it's being written) ─────────────────

  function startFile(path, language) {
    const lang = language || detectLanguage(path);
    _state.streamingFiles[path] = {
      path: path,
      content: '',
      language: lang,
      startTime: Date.now(),
    };
    // Add to files list immediately so it appears in tree
    if (!_state.files[path]) {
      _state.files[path] = {
        path: path,
        content: '',
        language: lang,
        updatedAt: new Date().toISOString(),
      };
      if (!_state.selectedPath) _state.selectedPath = path;
      refresh();
    }
  }

  function appendContent(content) {
    // Append to all active streaming files (in case multiple write tools run)
    Object.keys(_state.streamingFiles).forEach(function (path) {
      _state.streamingFiles[path].content = content;
      // Also update the preview in real-time for streaming files
      const file = _state.files[path];
      if (file) {
        file.content = content;
        file.updatedAt = new Date().toISOString();
      }
    });
    // Refresh preview if a streaming file is selected
    if (_state.selectedPath && _state.streamingFiles[_state.selectedPath]) {
      const previewContainer = document.getElementById('cp-preview-area');
      if (previewContainer) renderPreview(previewContainer);
    }
  }

  function syncState(files) {
    // Sync from external state (e.g. workspace_refresh event)
    Object.keys(files || {}).forEach(function (path) {
      const f = files[path];
      _state.files[path] = {
        path: path,
        content: f.content || '',
        language: f.language || detectLanguage(path),
        updatedAt: new Date().toISOString(),
      };
      delete _state.streamingFiles[path];
    });
    refresh();
  }

  // ─── Public API ─────────────────────────────────────────────────────────────

  function addFile(fileData) {
    const path = fileData.path;
    _state.files[path] = {
      path: path,
      content: fileData.content || '',
      language: fileData.language || detectLanguage(path),
      updatedAt: new Date().toISOString(),
    };
    if (!_state.selectedPath) _state.selectedPath = path;
    refresh();
    // Emit event for other components
    window.dispatchEvent(new CustomEvent('code:file_added', { detail: _state.files[path] }));
  }

  function updateFile(path, content) {
    if (!_state.files[path]) {
      addFile({ path: path, content: content });
      return;
    }
    _state.files[path].content = content;
    _state.files[path].updatedAt = new Date().toISOString();
    refresh();
    window.dispatchEvent(new CustomEvent('code:file_updated', { detail: _state.files[path] }));
  }

  function deleteFile(path) {
    delete _state.files[path];
    if (_state.selectedPath === path) {
      _state.selectedPath = Object.keys(_state.files)[0] || null;
    }
    refresh();
    window.dispatchEvent(new CustomEvent('code:file_deleted', { detail: { path: path } }));
  }

  function clearAll() {
    _state.files = {};
    _state.selectedPath = null;
    refresh();
    window.dispatchEvent(new CustomEvent('code:session_clear', { detail: {} }));
  }

  function selectFile(path) {
    _state.selectedPath = path;
    const treeContainer = document.getElementById('cp-file-tree');
    const previewContainer = document.getElementById('cp-preview-area');
    if (treeContainer) renderFileTree(treeContainer);
    if (previewContainer) renderPreview(previewContainer);
  }

  function toggleFolder(key, rowEl) {
    if (!rowEl) {
      rowEl = document.querySelector('.cp-folder-row[data-key="' + key + '"]');
    }
    const chevron = rowEl ? rowEl.querySelector('.cp-chevron') : null;
    const icon = rowEl ? rowEl.querySelector('.cp-folder-icon') : null;
    const isOpen = _state.expandedPaths.has(key);

    if (isOpen) {
      _state.expandedPaths.delete(key);
    } else {
      _state.expandedPaths.add(key);
    }

    const newOpen = _state.expandedPaths.has(key);
    if (chevron) {
      chevron.classList.toggle('open', newOpen);
      chevron.classList.remove('fa-chevron-right');
      chevron.classList.add(newOpen ? 'fa-chevron-down' : 'fa-chevron-right');
    }
    if (icon) {
      icon.classList.toggle('open', newOpen);
      icon.classList.remove('fa-folder', 'fa-folder-open');
      icon.classList.add(newOpen ? 'fa-folder-open' : 'fa-folder');
    }

    // Rebuild tree to show/hide children
    const treeContainer = document.getElementById('cp-file-tree');
    if (treeContainer) renderFileTree(treeContainer);
  }

  function copyFile(path) {
    const f = _state.files[path];
    if (!f) return;
    navigator.clipboard.writeText(f.content).then(function () {
      showCpToast('Copied to clipboard!');
    }).catch(function () {
      showCpToast('Copy failed', 'error');
    });
  }

  function downloadFile(path) {
    const f = _state.files[path];
    if (!f) return;
    const blob = new Blob([f.content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = path.split('/').pop();
    a.click();
    URL.revokeObjectURL(url);
    showCpToast('Downloaded ' + a.download);
  }

  function syncToGitHub(path) {
    window.dispatchEvent(new CustomEvent('github:sync_file', {
      detail: { path: path, content: (_state.files[path] || {}).content }
    }));
  }

  function refresh() {
    const treeContainer = document.getElementById('cp-file-tree');
    const previewContainer = document.getElementById('cp-preview-area');
    const countEl = document.getElementById('cp-file-count');
    if (countEl) countEl.textContent = Object.keys(_state.files).length + ' files';
    if (treeContainer) renderFileTree(treeContainer);
    if (previewContainer) renderPreview(previewContainer);
  }

  function getFiles() {
    return Object.values(_state.files);
  }

  function getFile(path) {
    return _state.files[path];
  }

  function formatTime(iso) {
    if (!iso) return '';
    const d = new Date(iso);
    const diff = Date.now() - d;
    const mins = Math.floor(diff / 60000);
    if (mins < 1) return 'just now';
    if (mins < 60) return mins + 'm ago';
    const hours = Math.floor(mins / 60);
    if (hours < 24) return hours + 'h ago';
    return d.toLocaleDateString();
  }

  // ─── Toast ─────────────────────────────────────────────────────────────────

  function showCpToast(msg, type) {
    const container = document.getElementById('cp-toast-container');
    if (!container) return;
    const t = document.createElement('div');
    t.className = 'cp-toast ' + (type || '');
    t.innerHTML = '<i class="fa-solid fa-' + (type === 'error' ? 'xmark' : 'check') + '"></i>' + escHtml(msg);
    container.appendChild(t);
    setTimeout(function () { t.remove(); }, 3000);
  }

  function escAttr(str) {
    if (!str) return '';
    return String(str).replace(/'/g, "\\'").replace(/"/g, '\\"');
  }

  // ─── Expose Global API ─────────────────────────────────────────────────────

  window.CodePanel = {
    addFile: addFile,
    updateFile: updateFile,
    deleteFile: deleteFile,
    clearAll: clearAll,
    selectFile: selectFile,
    toggleFolder: toggleFolder,
    copyFile: copyFile,
    downloadFile: downloadFile,
    syncToGitHub: syncToGitHub,
    refresh: refresh,
    getFiles: getFiles,
    getFile: getFile,
    startFile: startFile,
    appendContent: appendContent,
    syncState: syncState,
    get state() { return _state; },
  };

  // Listen for external file events (from other components)
  // Note: code:file_added is NOT re-dispatched to avoid infinite loop
  window.addEventListener('code:file_updated', function (e) { updateFile(e.detail.path, e.detail.content); });
  window.addEventListener('code:file_deleted', function (e) { deleteFile(e.detail.path); });
  window.addEventListener('code:session_clear', function () { clearAll(); });

})();
