# Regional HELM Script (not supposed to be modified by application team)
HELM_CHART_VERSION=2.7.0
HELM_TEMPLATE_BRANCH=release/v2.8.0.RC2
HELM_TEMPLATE_REPO=git@github.com:mfc-ets/rsf-helm-template.git
snykRepoBranch=release/RSF-1.0.0
noAllProjectForSnyk=true

#======== Application Specific Configuration ========
pythonBaseImageTag=1.0.0.RC1
deployToAlicloud=true

K8S_TARGET_NAMESPACE=ns-hkg-alicloud-system
K8S_PATH=k8s

EMAIL_RECIPIENT_LIST=Q_Qian_Jiang@manulife.com

bgDeploy=true

skipUnitTest=true
unitTestCommand=-m pytest -s tests/*.py

isEmergency=08102025